# Generated by Django 4.2.7 on 2025-01-25 20:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vendor", "0001_initial"),
        ("store", "0003_cartorder_cartorderitem_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="brand.jpg",
                        null=True,
                        upload_to=userauths.models.user_directory_path,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=1000)),
                (
                    "discount",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvxyz",
                        length=10,
                        max_length=25,
                        prefix="",
                    ),
                ),
                (
                    "used_by",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_vendor",
                        to="vendor.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryCouriers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=1000, null=True)),
                ("tracking_website", models.URLField(blank=True, null=True)),
                (
                    "url_parameter",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Delivery Couriers",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="cartorder",
            options={"ordering": ["-date"], "verbose_name_plural": "Cart Order"},
        ),
        migrations.AlterModelOptions(
            name="cartorderitem",
            options={"ordering": ["-date"], "verbose_name_plural": "Cart Order Item"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"ordering": ["date"], "verbose_name_plural": "Product Images"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"], "verbose_name_plural": "Products"},
        ),
        migrations.RenameField(
            model_name="cartorder",
            old_name="shipping_fee",
            new_name="shipping_amount",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="shipping_fee",
            new_name="shipping_amount",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="shipping_fee",
        ),
        migrations.RemoveField(
            model_name="cartorder",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="country",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="shipping_fee",
        ),
        migrations.RemoveField(
            model_name="color",
            name="date",
        ),
        migrations.RemoveField(
            model_name="size",
            name="date",
        ),
        migrations.RemoveField(
            model_name="specification",
            name="description",
        ),
        migrations.AddField(
            model_name="cart",
            name="shipping_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="applied_coupon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("On Hold", "On Hold"),
                    ("Shipping Processing", "Shipping Processing"),
                    ("Shipped", "Shipped"),
                    ("Arrived", "Arrived"),
                    ("Delivered", "Delivered"),
                    ("Returning", "Returning"),
                    ("Returned", "Returned"),
                ],
                default="On Hold",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="expected_delivery_date_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="expected_delivery_date_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="order_placed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="processing_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="product_arrived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="product_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="product_shipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="quality_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="shipping_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Estimated Shipping Fee = shipping_fee * total",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name="color",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to=userauths.models.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="digital",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="hot_deal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="orders",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="saved",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                length=5,
                max_length=50,
                prefix="SKU",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="special_offer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("auction", "Auction"),
                    ("offer", "Offer"),
                ],
                default="regular",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="specification",
            name="content",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="qty",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="service_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="sub_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="tax_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="email",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="full_name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="initial_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The original total before discounts",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="mobile",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="oid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvxyz",
                length=10,
                max_length=25,
                prefix="",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Fulfilled", "Fulfilled"),
                    ("Partially Fulfilled", "Partially Fulfilled"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("cancelled", "Cancelled"),
                    ("initiated", "Initiated"),
                    ("failed", "failed"),
                    ("refunding", "refunding"),
                    ("refunded", "refunded"),
                    ("unpaid", "unpaid"),
                    ("expired", "expired"),
                ],
                default="initiated",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="saved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Amount saved by customer",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="initial_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Grand Total of all amount listed above before discount",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="oid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvxyz",
                length=10,
                max_length=25,
                prefix="",
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitem",
                to="store.cartorder",
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="qty",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="saved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Amount saved by customer",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="service_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Estimated Service Fee = service_fee * total (paid by buyer to platform)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total of Product price * Product Qty",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="tax_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Estimated Vat based on delivery country = tax_rate * (total + shipping)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Grand Total of all amount listed above",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendor.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="category.jpg",
                null=True,
                upload_to=userauths.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="color_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="gid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvxyz",
                length=10,
                max_length=25,
                prefix="",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.FileField(
                default="gallery.jpg", upload_to=userauths.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True,
                default="product.jpg",
                null=True,
                upload_to=userauths.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvxyz",
                length=10,
                max_length=20,
                prefix="",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("disabled", "Disabled"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                ],
                default="published",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor",
                to="vendor.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="views",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wishlist",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("active", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=30, unique=True, verbose_name="Tag slug"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tags",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("reply", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        default=None,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "helpful",
                    models.ManyToManyField(
                        blank=True, related_name="helpful", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "not_helpful",
                    models.ManyToManyField(
                        blank=True,
                        related_name="not_helpful",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reviews & Rating",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProductFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvxyz",
                        length=10,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("question", models.CharField(max_length=1000)),
                ("answer", models.CharField(blank=True, max_length=10000, null=True)),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_faq",
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Faqs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.cartorder",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.cartorderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendor.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification",
            },
        ),
        migrations.CreateModel(
            name="CouponUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=1000)),
                ("mobile", models.CharField(max_length=1000)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.coupon"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.cartorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CancelledOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("refunded", models.BooleanField(default=False)),
                (
                    "orderitem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.cartorderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cancelled Order",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("town_city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=100)),
                ("status", models.BooleanField(default=False)),
                ("same_as_billing_address", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Address",
            },
        ),
        migrations.AddField(
            model_name="cartorder",
            name="coupons",
            field=models.ManyToManyField(blank=True, to="store.coupon"),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="coupon",
            field=models.ManyToManyField(blank=True, to="store.coupon"),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="delivery_couriers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.deliverycouriers",
            ),
        ),
    ]
